title = "Liberty for Hong Kong"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "About"
      url = "/about/"
	  
    [[menu.header]]
      weight = 3
      name = "Philosophy"
	  identifier = "philosophy"
      url = "#"
	  
	[[menu.header]]
      Name = "Concepts (coming soon)"
      parent = "philosophy"
      URL = "#"
      Weight = 1.0
	
	[[menu.header]]
      Name = "Slogans"
      parent = "philosophy"
      URL = "/slogans/"
      Weight = 1.0

	[[menu.header]]
      Name = "Glossary (coming soon)"
      parent = "philosophy"
      URL = "#"
      Weight = 1.0
	
	[[menu.header]]
      Name = "Artefacts"
      identifier = "artefacts"
      URL = "#"
      Weight = 4

	[[menu.header]]
      Name = "Art"
      parent = "artefacts"
      URL = "/art/"
      Weight = 1.0

	[[menu.header]]
      Name = "Music"
      parent = "artefacts"
      URL = "/music/"
      Weight = 2.0
	
	[[menu.header]]
      Name = "Writing"
      parent = "artefacts"
      URL = "/writing/"
      Weight = 3.0
	
	[[menu.header]]
      weight = 4.0
	  identifier = "facts"
      name = "Facts"
      url = "#"	  
    
	[[menu.header]]
      weight = 1.0
      name = "Timeline"
      parent = "facts"
      url = "/timeline-aelab/"

	[[menu.header]]
      weight = 2.0
      name = "Fact Check (coming soon)"
      parent = "facts"
      url = "#"
	
	[[menu.header]]
      weight = 3.0
      name = "Documentary (coming soon)"
      parent = "facts"
      url = "#"
	
	[[menu.header]]
      weight = 7
      name = "Contribute"
      url = "/contribute/"

    [[menu.footer]]
      weight = 1
      name = "About"
      url = "/about/"
	  
	[[menu.footer]]
      weight = 7
      name = "Contribute"
      url = "/contribute/"
	  
#  [[menu.footer]]
#      weight = 2
#      name = "Contact us"
#      url = "contact"
#    [[menu.footer]]
#      weight = 3
#      name = "How it works"
#      url = "work"
#    [[menu.footer]]
#      weight = 4
#      name = "Blog"
#      url = "blog"
#    [[menu.footer]]
#      weight = 5
#      name = "Terms"
#      url = "#"

  [params.logo]
    logo_path = "img/site-images/banner.png"
	
  [params.slider]
    enable = true
    title = "Liberty for Hong Kong"
    subtitle = "A collaborative project documenting Hong Kong's road to freedom"
    bgImage = "img/612-central.jpg"
    btnText = "Discover"
    url = "/about/"

  [params.wrapper]
    enable = true
    image = "img/hk-teargas-tennis.jpg"
    title = "About L4HK"
    italic = "L4HK is a collaborative project to crowdsource and document Hong Kong's journey to achieving meaningful freedom, democracy, and autonomy. This project was first created in the wake of the 2019 Anti-Extradition Bill protests."

  [params.blog]
    enable = false
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"
  
  [params.see_more]
    enable = true
    icon = "fa fa-fist-raised"
    title = "Revolution of Our Time"
    subtitle = "How it all started"
    link_url = "/timeline-aelab/"
    link_text = "See more"

  [params.feature]
    enable = true
    title = "Liberate Hong Kong, A Revolution of Our Time"
    bgImage = "img/calendar-protest-wide.jpg"
    content = "The 2019 protests were more than merely opposition against a legislative bill. It was a fully fledged movement that helped Hong Kongers discovered their identity, and generated large volumes of cultural artefacts such as music and art."
    [params.feature.button]
      caption = "View more"
      url = "/about/"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Contribute"
    paragraph = "Don't let our work be neglected or forgotten. You can contribute text, code, images, or videos - simply submit a pull a request on GitHub."
	
    [params.call.button]
      url = "/contribute/"
      text = "Contribute"

  [params.contact]
    enable = false
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
